version: '3.3'

services:
  mongodb:
    image: mongo:latest
    volumes:
      - mongodb:/data/db
      - mongodb_config:/data/configdb
    ports:
      - "27017:27017"


  api:
    depends_on:
      - mongodb
    image: bkidocks/todo-list-dock:latest
    ports:
      - "3000:3000"
      - "3001:3001"

volumes:
  mongodb:
  mongodb_config:
